version: '3.7'

services:
  eunomia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - .config.yml:/app/.config.yml
      - ./data:/app/data
    
networks:
  default:
    external: true
    name: compose-ingress