services:
  app:
    restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile.doreamon
    image: whatwewant/connect-doreamon:v1
    # command: sleep 1000000
    # platform: linux/amd64
    ports:
      - 0.0.0.0:8080:8080 # webhook
    environment:
      DEBUG: ${DEBUG}
      SESSION_KEY: ${SESSION_KEY}
      UPSTREAM: ${UPSTREAM}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
      FRONTEND: ${FRONTEND}
      BACKEND: ${BACKEND}
